function dummy_obj(userName, userEMail, userPassword, userPasswordConfirm) {
  return {
    userName: userName,
    userEMail: userEMail.toLowerCase(),
    userPassword: userPassword,
    userPasswordConfirm: userPasswordConfirm,
    contacts: [
      {
        name: "Ash Ketchum",
        email: "ash@pokemon.com",
        phone: "159159159",
        colorCode: "#f94144",
        textColorCode: "white",
      },
      {
        name: "Bart Simpson",
        email: "bart@simpsons.com",
        phone: "1234567890",
        colorCode: "#f3722c",
        textColorCode: "black",
      },
      {
        name: "Bisasam",
        email: "bisasam@pokemon.com",
        phone: "2468101214",
        colorCode: "#09be6d",
        textColorCode: "white",
      },
      {
        name: "Duffman",
        email: "duffman@duff.com",
        phone: "3434343434",
        colorCode: "#277da1",
        textColorCode: "white",
      },
      {
        name: "Eichhörnchen Scrat",
        email: "scrat@iceage.com",
        phone: "4242424242",
        colorCode: "#f9c74f",
        textColorCode: "black",
      },
      {
        name: "Eric Cartman",
        email: "cartman@southpark.com",
        phone: "0303030303",
        colorCode: "#577590",
        textColorCode: "white",
      },
      {
        name: "Faultier Sid",
        email: "sid@iceage.com",
        phone: "6767676767",
        colorCode: "#43aa8b",
        textColorCode: "black",
      },
      {
        name: "Glumanda",
        email: "glumanda@pokemon.com",
        phone: "9876543210",
        colorCode: "#ff4500",
        textColorCode: "white",
      },
      {
        name: "Helloworld",
        email: "planet@vegetacom",
        phone: "01751234658",
        colorCode: "#43da86",
        textColorCode: "black",
      },
      {
        name: "Homer Simpson",
        email: "homer@springfield.com",
        phone: "1234567890",
        colorCode: "#d0d256",
        textColorCode: "black",
      },
      {
        name: "Kakarott",
        email: "planet@vegeta.com",
        phone: "01751234658",
        colorCode: "#82e1f2",
        textColorCode: "black",
      },
      {
        name: "Kenny Mccormick",
        email: "kenny@southpark.com",
        phone: "3692581470",
        colorCode: "#4d908e",
        textColorCode: "white",
      },
      {
        name: "Mammut Manny",
        email: "manny@iceage.com",
        phone: "9876543210",
        colorCode: "#bb3e03",
        textColorCode: "white",
      },
      {
        name: "Max",
        email: "max.katze@bluewin.ch",
        phone: "0041796545860",
        colorCode: "#daa344",
        textColorCode: "black",
      },
      {
        name: "Mr Burns",
        email: "mr.burns@springfield.com",
        phone: "5757575757",
        colorCode: "#0a9396",
        textColorCode: "white",
      },
      {
        name: "Patrick Star",
        email: "patrick@spongebob.com",
        phone: "987987987",
        colorCode: "#8fda44",
        textColorCode: "black",
      },
      {
        name: "Philipp Wendschuch",
        email: "phndschuch@web.de",
        phone: "017367593",
        colorCode: "#43da86",
        textColorCode: "black",
      },
      {
        name: "Pika Pikachu",
        email: "pikachu@pokemon.com",
        phone: "5757575757",
        colorCode: "#f1d627",
        textColorCode: "black",
      },
      {
        name: "Son Goku",
        email: "goku@dbz.com",
        phone: "8989898989",
        colorCode: "#ff0066",
        textColorCode: "white",
      },
      {
        name: "Spongebob Schwammkopf",
        email: "spongebob@spongebob.com",
        phone: "1234567890",
        colorCode: "#c6d747",
        textColorCode: "black",
      },
      {
        name: "Stan Marsh",
        email: "stan@southpark.com",
        phone: "9876543210",
        colorCode: "#4462da",
        textColorCode: "white",
      },
      {
        name: "Vegeta",
        email: "vegeta@dbz.com",
        phone: "9876543210",
        colorCode: "#005f73",
        textColorCode: "white",
      },
      {
        name: "Silas Voss",
        email: "Silas@voss.com",
        phone: "1525664356",
        colorCode: "#43da86",
        textColorCode: "black",
      },
    ],
    tasks: {
      titles: [
        "Verloren im Poké-Dschungel",
        "Duff Time!",
        "OMG, Sie haben Kenny getötet!",
        "Crossover-Chaos!",
        "Geheimen Krabbenburger-Zutat",
        "D`oh & Dare: Homer vs. Bart",
        "Scrat´s Nuss-Odyssee",
      ],
      descriptions: [
        " Schnapp dir deinen Pokéball und mach dich bereit für ein wildes Abenteuer! Verirre dich durch hohe Gräser, erkunde geheimnisvolle Höhlen und triff auf Pokémon, die darauf warten, von dir entdeckt zu werden. Aber pass auf - Team Rocket könnte hinter jeder Ecke lauern! ",
        'Duffman und Homer Simpson treffen sich für ein episches Bier-Duell! "Sie rauchen 2 Zigaretten?!..!!!"',
        "",
        "Springfield trifft auf Pokémon, Ice Age, South Park, SpongeBob Schwammkopf und Dragonball Z!",
        "Irgendwo in Bikini Bottom ist die geheime Krabbenburger-Zutat.",
        "Homer und Bart liefern sich ein episches Duell",
        "Scrat ist wieder mal auf der Jagd nach seiner geliebten Nuss, aber wo ist sie?",
      ],
      assignedTo: [
        {
          colorCodes: [
            "rgb(249, 65, 68)",
            "rgb(9, 190, 109)",
            "rgb(255, 69, 0)",
            "rgb(241, 214, 39)",
          ],
          initials: ["AK", "B", "G", "PP"],
          textColors: [
            "rgb(255, 255, 255)",
            "rgb(255, 255, 255)",
            "rgb(255, 255, 255)",
            "rgb(0, 0, 0)",
          ],
          userMails: [
            "ash@pokemon.com",
            "bisasam@pokemon.com",
            "glumanda@pokemon.com",
            "pikachu@pokemon.com",
          ],
          userNames: ["Ash Ketchum", "Bisasam", "Glumanda", "Pika Pikachu"],
        },
        {
          colorCodes: [
            "rgb(39, 125, 161)",
            "rgb(208, 210, 86)",
            "rgb(249, 65, 68)",
            "rgb(243, 114, 44)",
          ],
          initials: ["D", "HS", "AK", "BS"],
          textColors: ["rgb(255, 255, 255)", "rgb(0, 0, 0)", "rgb(255, 255, 255)", "rgb(0, 0, 0)"],
          userMail: [
            "duffman@duff.com",
            "homer@springfield.com",
            "ash@pokemon.com",
            "bart@simpsons.com",
          ],
          userNames: ["Duffman", "Homer Simpson", "Ash Ketchum", "Bart Simpson"],
        },
        {
          colorCodes: ["rgb(87, 117, 144)", "rgb(68, 98, 218)"],
          initials: ["EC", "SM"],
          textColors: ["rgb(255, 255, 255)", "rgb(255, 255, 255)"],
          userMails: ["cartman@southpark.com", "stan@southpark.com"],
          userNames: ["Eric Cartman", "Stan Marsh"],
        },
        {
          colorCodes: [
            "rgb(249, 65, 68)",
            "rgb(243, 114, 44)",
            "rgb(9, 190, 109)",
            "rgb(39, 125, 161)",
            "rgb(249, 199, 79)",
            "rgb(87, 117, 144)",
            "rgb(67, 170, 139)",
            "rgb(255, 69, 0)",
            "rgb(208, 210, 86)",
            "rgb(77, 144, 142)",
            "rgb(187, 62, 3)",
            "rgb(218, 163, 68)",
            "rgb(10, 147, 150)",
            "rgb(143, 218, 68)",
            "rgb(241, 214, 39)",
            "rgb(255, 0, 102)",
            "rgb(198, 215, 71)",
            "rgb(68, 98, 218)",
            "rgb(0, 95, 115)",
          ],
          initials: [
            "AK",
            "BS",
            "B",
            "D",
            "ES",
            "EC",
            "FS",
            "G",
            "HS",
            "KM",
            "MM",
            "M",
            "MB",
            "PS",
            "PP",
            "SG",
            "SS",
            "SM",
            "V",
          ],
          textColors: [
            "rgb(255, 255, 255)",
            "rgb(0, 0, 0)",
            "rgb(255, 255, 255)",
            "rgb(255, 255, 255)",
            "rgb(0, 0, 0)",
            "rgb(255, 255, 255)",
            "rgb(0, 0, 0)",
            "rgb(255, 255, 255)",
            "rgb(0, 0, 0)",
            "rgb(255, 255, 255)",
            "rgb(255, 255, 255)",
            "rgb(0, 0, 0)",
            "rgb(255, 255, 255)",
            "rgb(0, 0, 0)",
            "rgb(0, 0, 0)",
            "rgb(255, 255, 255)",
            "rgb(0, 0, 0)",
            "rgb(255, 255, 255)",
            "rgb(255, 255, 255)",
          ],
          userMails: [
            "ash@pokemon.com",
            "bart@simpsons.com",
            "bisasam@pokemon.com",
            "duffman@duff.com",
            "scrat@iceage.com",
            "cartman@southpark.com",
            "sid@iceage.com",
            "glumanda@pokemon.com",
            "homer@springfield.com",
            "kenny@southpark.com",
            "manny@iceage.com",
            "max.katze@bluewin.ch",
            "mr.burns@springfield.com",
            "patrick@spongebob.com",
            "pikachu@pokemon.com",
            "goku@dbz.com",
            "spongebob@spongebob.com",
            "stan@southpark.com",
            "vegeta@dbz.com",
          ],
          userNames: [
            "Ash Ketchum",
            "Bart Simpson",
            "Bisasam",
            "Duffman",
            "Eichhörnchen Scrat",
            "Eric Cartman",
            "Faultier Sid",
            "Glumanda",
            "Homer Simpson",
            "Kenny Mccormick",
            "Mammut Manny",
            "Max",
            "Mr Burns",
            "Patrick Star",
            "Pika Pikachu",
            "Son Goku",
            "Spongebob Schwammkopf",
            "Stan Marsh",
            "Vegeta",
          ],
        },
        {
          colorCodes: ["rgb(143, 218, 68)", "rgb(198, 215, 71)"],
          initials: ["PS", "SS"],
          textColors: ["rgb(0, 0, 0)", "rgb(0, 0, 0)"],
          userMails: ["patrick@spongebob.com", "spongebob@spongebob.com"],
          userNames: ["Patrick Star", "Spongebob Schwammkopf"],
        },
        {
          colorCodes: ["rgb(243, 114, 44)", "rgb(208, 210, 86)"],
          initials: ["BS", "HS"],
          textColors: ["rgb(0, 0, 0)", "rgb(0, 0, 0)"],
          userMails: ["bart@simpsons.com", "homer@springfield.com"],
          userNames: ["Bart Simpson", "Homer Simpson"],
        },
        {
          colorCodes: ["rgb(249, 199, 79)", "rgb(67, 170, 139)", "rgb(187, 62, 3)"],
          initials: ["ES", "FS", "MM"],
          textColors: ["rgb(0, 0, 0)", "rgb(0, 0, 0)", "rgb(255, 255, 255)"],
          userMails: ["scrat@iceage.com", "sid@iceage.com", "manny@iceage.com"],
          userNames: ["Eichhörnchen Scrat", "Faultier Sid", "Mammut Manny"],
        },
      ],
      prios: ["urgent", "low", "urgent", "low", "medium", "low", "low"],
      categories: [
        "User Story",
        "Research",
        "Technical Task",
        "Enhancement",
        "Feature Request",
        "Other",
        "Infrastructure",
      ],
      subtasks: [
        {
          done: [true, true],
          tasks: ["Finde deinen Weg durch den Poké-Dschungel.", "Besiege Team Rocket!"],
        },
        {
          done: [false, false, false],
          tasks: [
            "Trinke ein Duff Beer schneller als Homer.",
            "Stelle sicher, dass der Kühlschrank für weitere Du",
            "sdawfawf",
          ],
        },
        {done: [], tasks: []},
        {done: [true], tasks: ["Bart und Ash gegen Mr. Burns und Team Rocket."]},
        {
          done: [true, false],
          tasks: [
            "Hilf Patrick, den besten Sonnenplatz am Meeresboden zu finden!",
            "Finde die geheime Krabbenburger-Zutat! ",
          ],
        },
        {done: [], tasks: []},
        {
          done: [false, false],
          tasks: [
            "Hilf Scrat, seine Nuss zu finden!",
            "Überzeuge Sid und Manny, Scrat bei seiner Suche zu helfen!",
          ],
        },
      ],
      dates: [
        "2024-04-26",
        "2024-04-21",
        "2024-04-24",
        "2024-04-28",
        "2024-04-18",
        "2024-05-03",
        "2024-04-22",
      ],
      board: ["done", "done", "toDo", "inProgress", "inProgress", "toDo", "awaitFeedback"],
    },
  };
}
